# Generated by Django 6.0.3 on 2026-03-23 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_status_options_rename_status_status_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
